name: Sync approved PRs to internal codebase
on:
  pull_request_target:
    types: [labeled]

jobs:
  sync_prs_to_internal_codebase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    if: |
      github.event.label.name == 'PR-Sync-Merge' ||
      github.event.label.name == 'PR-Sync-Rebase' ||
      github.event.label.name == 'PR-Sync-Update'
    steps:
      - uses: actions/checkout@v4

      - name: Sync approved PRs to internal codebase
        uses: OpenSiFli/sync-pr-to-gitlab@v2
        with:
          github_token: ${{ github.token }}
          gitlab_url: ${{ secrets.GITLAB_URL }}
          gitlab_namespace: ${{ secrets.GITLAB_NAMESPACE }}
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          git_config_name: ${{ secrets.GIT_CONFIG_NAME }}
          git_config_email: ${{ secrets.GIT_CONFIG_EMAIL }}